import { ActionPlan, TeamMember, ActivityLog, Comment, Attachment } from '@/types';

// Sample team members
export const teamMembers: TeamMember[] = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    role: 'Senior Developer',
    skills: ['Frontend', 'React', 'TypeScript', 'UI/UX'],
    workload: 8,
    availability: {
      status: 'available',
      timeOff: [],
    },
  },
  {
    id: '2',
    name: 'Jane Smith',
    email: 'jane@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    role: 'Project Manager',
    skills: ['Leadership', 'Communication', 'Planning', 'Agile'],
    workload: 12,
    availability: {
      status: 'busy',
      timeOff: [
        {
          start: new Date(2025, 11, 15),
          end: new Date(2025, 11, 20),
          reason: 'Vacation',
        },
      ],
    },
  },
  {
    id: '3',
    name: 'Mike Johnson',
    email: 'mike@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
    role: 'Backend Developer',
    skills: ['Backend', 'Node.js', 'Database', 'API Design'],
    workload: 6,
    availability: {
      status: 'available',
      timeOff: [],
    },
  },
  {
    id: '4',
    name: 'Sarah Williams',
    email: 'sarah@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    role: 'UX Designer',
    skills: ['Design', 'Figma', 'User Research', 'Prototyping'],
    workload: 5,
    availability: {
      status: 'available',
      timeOff: [
        {
          start: new Date(2025, 11, 10),
          end: new Date(2025, 11, 12),
          reason: 'Conference',
        },
      ],
    },
  },
  {
    id: '5',
    name: 'Alex Chen',
    email: 'alex@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    role: 'DevOps Engineer',
    skills: ['DevOps', 'AWS', 'Docker', 'CI/CD'],
    workload: 7,
    availability: {
      status: 'away',
      timeOff: [],
    },
  },
];

// Sample action plans with new structure
export const actionPlans: ActionPlan[] = [
  {
    id: 'AP-1',
    title: 'Complete project documentation',
    what: {
      description: 'Write comprehensive documentation for the new feature including API references, user guides, and code examples',
      successCriteria: [
        'All API endpoints documented',
        'User guide with screenshots',
        'Code examples for common use cases',
      ],
      requiredResources: ['Technical writer review', 'Access to staging environment'],
    },
    who: {
      primaryAssignee: teamMembers[0],
      supportingMembers: [teamMembers[1]],
      stakeholders: [teamMembers[3]],
    },
    when: {
      dueDate: new Date('2025-12-05'),
      timeEstimate: 16,
      reminderSettings: {
        enabled: true,
        reminderDate: new Date('2025-12-04'),
      },
    },
    priority: 'high',
    status: 'in-progress',
    tags: ['documentation', 'feature', 'priority'],
    dependencies: [],
    createdAt: new Date('2025-11-20'),
    createdBy: 'John Doe',
    updatedAt: new Date('2025-11-28'),
    statusHistory: [
      { from: 'pending', to: 'in-progress', changedAt: new Date('2025-11-22'), changedBy: 'John Doe' },
    ],
  },
  {
    id: 'AP-2',
    title: 'Review code changes for security updates',
    what: {
      description: 'Review PR #234 for security updates and ensure all vulnerabilities are addressed',
      successCriteria: [
        'All security issues resolved',
        'Code follows security best practices',
        'No performance regressions',
      ],
      requiredResources: ['Security checklist', 'Test environment'],
    },
    who: {
      primaryAssignee: teamMembers[1],
      supportingMembers: [teamMembers[2]],
      stakeholders: [teamMembers[0], teamMembers[3]],
    },
    when: {
      dueDate: new Date('2025-12-03'),
      timeEstimate: 8,
      reminderSettings: {
        enabled: true,
        reminderDate: new Date('2025-12-02'),
      },
    },
    priority: 'critical',
    status: 'pending',
    tags: ['security', 'code-review', 'urgent'],
    dependencies: [],
    createdAt: new Date('2025-11-25'),
    createdBy: 'Jane Smith',
    updatedAt: new Date('2025-11-25'),
    statusHistory: [],
  },
  {
    id: 'AP-3',
    title: 'Deploy to staging environment',
    what: {
      description: 'Deploy latest build to staging for comprehensive QA testing',
      successCriteria: [
        'Deployment successful',
        'All services running',
        'Database migrations complete',
      ],
      requiredResources: ['Staging credentials', 'Deployment checklist'],
    },
    who: {
      primaryAssignee: teamMembers[2],
      supportingMembers: [],
      stakeholders: [teamMembers[1], teamMembers[3]],
    },
    when: {
      dueDate: new Date('2025-11-28'),
      timeEstimate: 4,
      reminderSettings: {
        enabled: false,
      },
    },
    priority: 'medium',
    status: 'blocked',
    tags: ['deployment', 'staging', 'devops'],
    dependencies: ['AP-2'],
    createdAt: new Date('2025-11-15'),
    createdBy: 'Mike Johnson',
    updatedAt: new Date('2025-11-26'),
    statusHistory: [
      { from: 'pending', to: 'blocked', changedAt: new Date('2025-11-26'), changedBy: 'Mike Johnson', reason: 'Waiting for security review' },
    ],
  },
  {
    id: 'AP-4',
    title: 'Update database schema',
    what: {
      description: 'Add new tables for user preferences and notification settings',
      successCriteria: [
        'Migration script tested',
        'Rollback plan documented',
        'Zero downtime deployment',
      ],
      requiredResources: ['Database admin access', 'Backup verification'],
    },
    who: {
      primaryAssignee: teamMembers[3],
      supportingMembers: [teamMembers[2]],
      stakeholders: [teamMembers[0]],
    },
    when: {
      dueDate: new Date('2025-11-25'),
      timeEstimate: 6,
      reminderSettings: {
        enabled: true,
      },
    },
    priority: 'high',
    status: 'completed',
    tags: ['database', 'migration', 'backend'],
    dependencies: [],
    createdAt: new Date('2025-11-10'),
    createdBy: 'Sarah Williams',
    updatedAt: new Date('2025-11-24'),
    completedAt: new Date('2025-11-24'),
    statusHistory: [
      { from: 'pending', to: 'in-progress', changedAt: new Date('2025-11-15'), changedBy: 'Sarah Williams' },
      { from: 'in-progress', to: 'completed', changedAt: new Date('2025-11-24'), changedBy: 'Sarah Williams' },
    ],
  },
  {
    id: 'AP-5',
    title: 'Design new landing page',
    what: {
      description: 'Create modern mockups for the new landing page with focus on conversion',
      successCriteria: [
        'Desktop and mobile designs',
        'Interactive prototype',
        'Stakeholder approval',
      ],
      requiredResources: ['Design system access', 'Brand guidelines'],
    },
    who: {
      primaryAssignee: teamMembers[1],
      supportingMembers: [teamMembers[4]],
      stakeholders: [teamMembers[0], teamMembers[3]],
    },
    when: {
      dueDate: new Date('2025-12-10'),
      timeEstimate: 20,
      reminderSettings: {
        enabled: true,
        reminderDate: new Date('2025-12-08'),
      },
    },
    priority: 'medium',
    status: 'in-progress',
    tags: ['design', 'ui/ux', 'landing-page'],
    dependencies: [],
    createdAt: new Date('2025-11-22'),
    createdBy: 'Jane Smith',
    updatedAt: new Date('2025-11-29'),
    statusHistory: [
      { from: 'pending', to: 'in-progress', changedAt: new Date('2025-11-25'), changedBy: 'Jane Smith' },
    ],
  },
  {
    id: 'AP-6',
    title: 'Fix authentication bug',
    what: {
      description: 'Resolve login issues with OAuth providers causing intermittent failures',
      successCriteria: [
        'OAuth flow working reliably',
        'Error handling improved',
        'User session persistence fixed',
      ],
      requiredResources: ['OAuth credentials', 'Test accounts'],
    },
    who: {
      primaryAssignee: teamMembers[0],
      supportingMembers: [],
      stakeholders: [teamMembers[1]],
    },
    when: {
      dueDate: new Date('2025-11-30'),
      timeEstimate: 6,
      reminderSettings: {
        enabled: true,
      },
    },
    priority: 'critical',
    status: 'completed',
    tags: ['bug', 'authentication', 'hotfix'],
    dependencies: [],
    createdAt: new Date('2025-11-18'),
    createdBy: 'John Doe',
    updatedAt: new Date('2025-11-29'),
    completedAt: new Date('2025-11-29'),
    statusHistory: [
      { from: 'pending', to: 'in-progress', changedAt: new Date('2025-11-19'), changedBy: 'John Doe' },
      { from: 'in-progress', to: 'completed', changedAt: new Date('2025-11-29'), changedBy: 'John Doe' },
    ],
  },
  {
    id: 'AP-7',
    title: 'Write unit tests for payment module',
    what: {
      description: 'Add comprehensive test coverage for payment processing functionality',
      successCriteria: [
        '90% code coverage achieved',
        'All edge cases covered',
        'Integration tests included',
      ],
      requiredResources: ['Test environment', 'Mock payment gateway'],
    },
    who: {
      primaryAssignee: teamMembers[2],
      supportingMembers: [teamMembers[0]],
      stakeholders: [],
    },
    when: {
      dueDate: new Date('2025-12-08'),
      timeEstimate: 12,
      reminderSettings: {
        enabled: true,
        reminderDate: new Date('2025-12-06'),
      },
    },
    priority: 'medium',
    status: 'pending',
    tags: ['testing', 'payment', 'quality'],
    dependencies: [],
    createdAt: new Date('2025-11-28'),
    createdBy: 'Mike Johnson',
    updatedAt: new Date('2025-11-28'),
    statusHistory: [],
  },
  {
    id: 'AP-8',
    title: 'Optimize database queries',
    what: {
      description: 'Improve performance of analytics queries causing slow dashboard loads',
      successCriteria: [
        'Query time reduced by 50%',
        'Proper indexes added',
        'Query plans optimized',
      ],
      requiredResources: ['Database profiler', 'Production data sample'],
    },
    who: {
      primaryAssignee: teamMembers[3],
      supportingMembers: [teamMembers[2]],
      stakeholders: [teamMembers[0]],
    },
    when: {
      dueDate: new Date('2025-12-15'),
      timeEstimate: 10,
      reminderSettings: {
        enabled: false,
      },
    },
    priority: 'low',
    status: 'pending',
    tags: ['performance', 'database', 'optimization'],
    dependencies: [],
    createdAt: new Date('2025-11-29'),
    createdBy: 'Sarah Williams',
    updatedAt: new Date('2025-11-29'),
    statusHistory: [],
  },
];

// Sample comments
export const comments: Comment[] = [
  {
    id: 'CMT-1',
    actionPlanId: 'AP-1',
    author: teamMembers[1],
    content: 'Great progress on the documentation! The API reference section looks comprehensive.',
    createdAt: new Date('2025-11-28T10:30:00'),
  },
  {
    id: 'CMT-2',
    actionPlanId: 'AP-1',
    author: teamMembers[0],
    content: 'Thanks! I\'ll have the user guide completed by tomorrow.',
    createdAt: new Date('2025-11-28T11:15:00'),
  },
  {
    id: 'CMT-3',
    actionPlanId: 'AP-2',
    author: teamMembers[2],
    content: 'I\'ve reviewed the security changes and they look solid. Just need to verify the authentication flow.',
    createdAt: new Date('2025-11-26T14:20:00'),
  },
  {
    id: 'CMT-4',
    actionPlanId: 'AP-6',
    author: teamMembers[0],
    content: 'Bug fixed! The issue was with the OAuth token refresh logic.',
    createdAt: new Date('2025-11-29T13:45:00'),
  },
  {
    id: 'CMT-5',
    actionPlanId: 'AP-5',
    author: teamMembers[4],
    content: 'The mobile designs need some adjustments for better usability.',
    createdAt: new Date('2025-11-29T09:10:00'),
  },
];

// Sample attachments
export const attachments: Attachment[] = [
  {
    id: 'ATT-1',
    actionPlanId: 'AP-1',
    name: 'API_Documentation_Draft.pdf',
    url: '/files/api-docs-draft.pdf',
    type: 'application/pdf',
    size: 2457600,
    uploadedBy: 'John Doe',
    uploadedAt: new Date('2025-11-25T09:00:00'),
  },
  {
    id: 'ATT-2',
    actionPlanId: 'AP-5',
    name: 'Landing_Page_Mockup_v1.fig',
    url: '/files/landing-mockup-v1.fig',
    type: 'application/figma',
    size: 5242880,
    uploadedBy: 'Jane Smith',
    uploadedAt: new Date('2025-11-26T14:30:00'),
  },
  {
    id: 'ATT-3',
    actionPlanId: 'AP-4',
    name: 'Database_Migration_Script.sql',
    url: '/files/migration-script.sql',
    type: 'text/plain',
    size: 8192,
    uploadedBy: 'Sarah Williams',
    uploadedAt: new Date('2025-11-20T16:45:00'),
  },
  {
    id: 'ATT-4',
    actionPlanId: 'AP-2',
    name: 'Security_Review_Checklist.xlsx',
    url: '/files/security-checklist.xlsx',
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    size: 15360,
    uploadedBy: 'Jane Smith',
    uploadedAt: new Date('2025-11-25T11:00:00'),
  },
];

// Sample activity logs
export const activityLogs: ActivityLog[] = [
  {
    id: 'LOG-1',
    actionPlanId: 'AP-1',
    actionTitle: 'Complete project documentation',
    type: 'created',
    performedBy: 'John Doe',
    timestamp: new Date('2025-11-20T09:00:00'),
    description: 'Created action plan',
  },
  {
    id: 'LOG-2',
    actionPlanId: 'AP-1',
    actionTitle: 'Complete project documentation',
    type: 'status_changed',
    performedBy: 'John Doe',
    timestamp: new Date('2025-11-22T10:30:00'),
    description: 'Changed status from pending to in-progress',
    changes: {
      status: { old: 'pending', new: 'in-progress' },
    },
  },
  {
    id: 'LOG-3',
    actionPlanId: 'AP-1',
    actionTitle: 'Complete project documentation',
    type: 'attachment_added',
    performedBy: 'John Doe',
    timestamp: new Date('2025-11-25T09:00:00'),
    description: 'Uploaded file: API_Documentation_Draft.pdf',
  },
  {
    id: 'LOG-4',
    actionPlanId: 'AP-1',
    actionTitle: 'Complete project documentation',
    type: 'comment_added',
    performedBy: 'Jane Smith',
    timestamp: new Date('2025-11-28T10:30:00'),
    description: 'Added a comment',
  },
  {
    id: 'LOG-5',
    actionPlanId: 'AP-6',
    actionTitle: 'Fix authentication bug',
    type: 'created',
    performedBy: 'John Doe',
    timestamp: new Date('2025-11-18T09:00:00'),
    description: 'Created action plan',
  },
  {
    id: 'LOG-6',
    actionPlanId: 'AP-6',
    actionTitle: 'Fix authentication bug',
    type: 'status_changed',
    performedBy: 'John Doe',
    timestamp: new Date('2025-11-19T10:00:00'),
    description: 'Changed status from pending to in-progress',
  },
  {
    id: 'LOG-7',
    actionPlanId: 'AP-6',
    actionTitle: 'Fix authentication bug',
    type: 'completed',
    performedBy: 'John Doe',
    timestamp: new Date('2025-11-29T14:30:00'),
    description: 'Marked as completed',
  },
  {
    id: 'LOG-8',
    actionPlanId: 'AP-4',
    actionTitle: 'Update database schema',
    type: 'created',
    performedBy: 'Sarah Williams',
    timestamp: new Date('2025-11-10T09:00:00'),
    description: 'Created action plan',
  },
  {
    id: 'LOG-9',
    actionPlanId: 'AP-4',
    actionTitle: 'Update database schema',
    type: 'completed',
    performedBy: 'Sarah Williams',
    timestamp: new Date('2025-11-24T16:45:00'),
    description: 'Marked as completed',
  },
  {
    id: 'LOG-10',
    actionPlanId: 'AP-3',
    actionTitle: 'Deploy to staging environment',
    type: 'status_changed',
    performedBy: 'Mike Johnson',
    timestamp: new Date('2025-11-26T13:20:00'),
    description: 'Changed status from pending to blocked',
  },
];

// Sample notifications
export const notifications = [
  {
    id: 'NOTIF-1',
    type: 'assignment' as const,
    title: 'New Assignment',
    message: 'You have been assigned to "Complete project documentation"',
    actionPlanId: 'AP-1',
    actionPlanTitle: 'Complete project documentation',
    relatedUserId: '2',
    relatedUserName: 'Jane Smith',
    timestamp: new Date('2025-12-01T09:00:00'),
    read: false,
  },
  {
    id: 'NOTIF-2',
    type: 'deadline_24h' as const,
    title: 'Deadline Approaching',
    message: '"Implement user authentication" is due in 24 hours',
    actionPlanId: 'AP-2',
    actionPlanTitle: 'Implement user authentication',
    timestamp: new Date('2025-12-01T14:00:00'),
    read: false,
  },
  {
    id: 'NOTIF-3',
    type: 'comment' as const,
    title: 'New Comment',
    message: 'Mike Johnson commented on "Deploy to staging environment"',
    actionPlanId: 'AP-3',
    actionPlanTitle: 'Deploy to staging environment',
    relatedUserId: '3',
    relatedUserName: 'Mike Johnson',
    timestamp: new Date('2025-11-30T16:30:00'),
    read: true,
  },
  {
    id: 'NOTIF-4',
    type: 'mention' as const,
    title: 'You were mentioned',
    message: 'Sarah Williams mentioned you in a comment',
    actionPlanId: 'AP-5',
    actionPlanTitle: 'Design new landing page',
    relatedUserId: '4',
    relatedUserName: 'Sarah Williams',
    timestamp: new Date('2025-11-30T10:15:00'),
    read: true,
  },
  {
    id: 'NOTIF-5',
    type: 'status_change' as const,
    title: 'Status Updated',
    message: '"Optimize database queries" status changed to completed',
    actionPlanId: 'AP-4',
    actionPlanTitle: 'Optimize database queries',
    relatedUserId: '3',
    relatedUserName: 'Mike Johnson',
    timestamp: new Date('2025-11-29T11:00:00'),
    read: true,
  },
];
